const topMovies = [
  {
    src: "https://images.plex.tv/photo?size=large-1280&url=https%3A%2F%2Fmetadata-static.plex.tv%2F6%2Fgracenote%2F6712d44cade77919f9365b7626aa37d7.jpg",
    title: "suzume",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/akurat/images/2023/03/big/img_64195ea53c50e0-97937540-78580199.JPG",
    title: "jurrasic",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BODRlNTY5ZjktZjE0Ni00YjZhLTk3NTItYzk0ZjYxN2QxMWEzXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_.jpg",
    title: "sonic",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BOTY1ZGM2YzQtMTBjZC00NjE2LWJlNzUtYjA0YjYxNzBjMmRjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg",
    title: "all-of-us",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://lumiere-a.akamaihd.net/v1/images/p_bighero6_19753_20bd6206.jpeg?region=0%2C0%2C540%2C810",
    title: "big-hero-6",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/id/f/f4/The_Little_Mermaid_%282023_film%29.png",
    title: "litle-mermaid",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://images.justwatch.com/poster/309791505/s718/duty-after-school.jpg",
    title: "duty-after-school",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://lumiere-a.akamaihd.net/v1/images/p_bighero6_19753_20bd6206.jpeg?region=0%2C0%2C540%2C810",
    title: "big-hero6",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BOTY1ZGM2YzQtMTBjZC00NjE2LWJlNzUtYjA0YjYxNzBjMmRjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg",
    title: "all-of-us",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://cdn0-production-images-kly.akamaized.net/Z5gXiKOXZ0AaSHp8KgaTJSQ0_1o=/800x1066/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/4334651/original/046648600_1677131777-20230223_125314.jpg",
    title: "missing",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "",
    title: "",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
];

const trendingMovies = [
  {
    src: "https://starzplay-img-prod-ssl.akamaized.net/474w/MGM/THETOMORROWWARY2021M/THETOMORROWWARY2021M-474x677-PST.jpg",
    title: "tomorrow-war",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BODZhNzlmOGItMWUyYS00Y2Q5LWFlNzMtM2I2NDFkM2ZkYmE1XkEyXkFqcGdeQXVyMTU5OTA4NTIz._V1_.jpg",
    title: "quantumania",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://lumiere-a.akamaihd.net/v1/images/id-guardiansofthegalaxy-vol3-payoffposter_6ba5c28b.jpeg",
    title: "gotg-3",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/id/8/80/A_Man_Called_Otto_poster.jpg",
    title: "otto",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/id/f/f4/The_Little_Mermaid_%282023_film%29.png",
    title: "litle-mermaid",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://images.plex.tv/photo?size=large-1280&url=https%3A%2F%2Fmetadata-static.plex.tv%2F6%2Fgracenote%2F6712d44cade77919f9365b7626aa37d7.jpg",
    title: "suzume",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/akurat/images/2023/03/big/img_64195ea53c50e0-97937540-78580199.JPG",
    title: "jurrasic",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BODRlNTY5ZjktZjE0Ni00YjZhLTk3NTItYzk0ZjYxN2QxMWEzXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_.jpg",
    title: "sonic",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BOTY1ZGM2YzQtMTBjZC00NjE2LWJlNzUtYjA0YjYxNzBjMmRjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg",
    title: "all-of-us",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://lumiere-a.akamaihd.net/v1/images/p_bighero6_19753_20bd6206.jpeg?region=0%2C0%2C540%2C810",
    title: "big-hero-6",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
];

const newRelease = [
  {
    src: "https://upload.wikimedia.org/wikipedia/id/f/f4/The_Little_Mermaid_%282023_film%29.png",
    title: "litle-mermaid",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://images.justwatch.com/poster/309791505/s718/duty-after-school.jpg",
    title: "duty-after-school",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://lumiere-a.akamaihd.net/v1/images/p_bighero6_19753_20bd6206.jpeg?region=0%2C0%2C540%2C810",
    title: "big-hero6",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BOTY1ZGM2YzQtMTBjZC00NjE2LWJlNzUtYjA0YjYxNzBjMmRjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg",
    title: "all-of-us",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://cdn0-production-images-kly.akamaized.net/Z5gXiKOXZ0AaSHp8KgaTJSQ0_1o=/800x1066/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/4334651/original/046648600_1677131777-20230223_125314.jpg",
    title: "missing",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "",
    title: "",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://images.plex.tv/photo?size=large-1280&url=https%3A%2F%2Fmetadata-static.plex.tv%2F6%2Fgracenote%2F6712d44cade77919f9365b7626aa37d7.jpg",
    title: "suzume",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/akurat/images/2023/03/big/img_64195ea53c50e0-97937540-78580199.JPG",
    title: "jurrasic",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BODRlNTY5ZjktZjE0Ni00YjZhLTk3NTItYzk0ZjYxN2QxMWEzXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_.jpg",
    title: "sonic",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://m.media-amazon.com/images/M/MV5BOTY1ZGM2YzQtMTBjZC00NjE2LWJlNzUtYjA0YjYxNzBjMmRjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg",
    title: "all-of-us",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
  {
    src: "https://lumiere-a.akamaihd.net/v1/images/p_bighero6_19753_20bd6206.jpeg?region=0%2C0%2C540%2C810",
    title: "big-hero-6",
    rating: "",
    episodes: "",
    genres: ["", "", ""],
  },
];

export { topMovies, trendingMovies, newRelease };
